[package]

serial = "2015061800"

name = "markov"
version = "0.0.2"
authors = ["Stacey Ell <stacey.ell@gmail.com>"], ["Kevin Waters <kevin.waters@gmail.com>"]

[lib]
name = "markov"
crate-type = ["dylib", "rlib"]
